# Generated by Django 5.2.4 on 2025-07-04 06:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caso", models.CharField(max_length=100, verbose_name="Caso")),
                ("nombres", models.CharField(max_length=200, verbose_name="Nombres")),
                (
                    "urgencia",
                    models.CharField(
                        choices=[
                            ("Alta", "Alta"),
                            ("Media", "Media"),
                            ("Baja", "Baja"),
                        ],
                        max_length=10,
                        verbose_name="Urgencia",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=300, verbose_name="Dirección"),
                ),
                (
                    "disposicion",
                    models.CharField(max_length=200, verbose_name="Disposición"),
                ),
                (
                    "condicion",
                    models.CharField(max_length=100, verbose_name="Condición"),
                ),
                ("fiscal", models.CharField(max_length=200, verbose_name="Fiscal")),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "documento_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL del Documento"
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Creador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "es_administrador",
                    models.BooleanField(default=False, verbose_name="Es Administrador"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
            },
        ),
    ]
