# Generated by Django 5.2.4 on 2025-07-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0001_initial"),
    ]

    operations = []
